### ISSUE TITLE
Arduino Uno R4 Wifi Support

### ISSUE THREAD

**Issue by leonpierre** [astuder/icp-101xx#11]
I tried to use my old sketch with the header icp101xx.h and `ICP101xx mysensor;` but got never a connection with the new Uno R4.
The sensor is connected over the Qwiic/Stemma connector on the board as it was before with the older Arduinos.

**Comment by astuder** [comment]
I don't have an Uno R4 to test. 

Based on what I can find on the internet, you may have to use Wire1 instead of just Wire depending on which I2C pins/ports you are using:
https://forum.arduino.cc/t/not-working-with-qwiic-devices/1143109

The icp-101xx library defaults to Wire, but you can pass in a different Wire object when calling begin. For example:
`mysensor.begin(&Wire1);`

Let me know if this solves your issue.

**Comment by leonpierre** [comment]
Thx, that solved the issue for me!
