### ISSUE TITLE
Question on temperature compensation expectations

### ISSUE THREAD

**Issue by smig23** [astuder/icp-101xx#6]
Hi Adrian,
nice work with the library. Just wondering if you could give me a sanity check on the expectations for temperature compensation for this sensor.

I recently acquired an ICP-10100 and hooked it up to a Teensy 3.2 running Teensyduino and used the library and blocking example ( with minor modification of the pressure offset to use the Arduino plotter effectively) to run a sanity check. Everything appears to function except the temperature compensation doesn't seem to work or doesn't appear to work very effectively.
The image below shows the effect of keeping the pressure constant and increasing the temperature. The effect is about a 20Pa change for 3 degrees of temperature change. Red is the pressure trace and blue is the temperature trace.

![image](https://user-images.githubusercontent.com/4381963/62842238-bb8d1f80-bc7e-11e9-9edc-d833b217f36b.png)

I looked through the code and see that it matches the datasheet for the calculation approach and includes the temperature compensation parameters in the calculations. My interpretation of the datasheet is that the temperature compensation should take care of this effect. 

I'm trying to understand if this is to be expected or if something isn't right with my setup. Appreciate any thoughts you can provide.

Cheers
Ian

**Comment by astuder** [comment]
Hi Ian,

I haven't systematically looked at how stable the sensor is across temperature. The relationship between temperature and pressure in your graph is very obvious. Looks like something that may be possible to calibrate out by tweaking some parameters in the temperature compensation code.

Is your test done in an open room, or do you use a confined test chamber? With the latter, the pressure change could be real.

Thinking back, I remember that the pressure reported by the sensor would drift slowly after being put onto the floor. I attributed that to actual pressure change, but in retrospect it could have been due to the lower air temperature.

The datasheet calls out mechanical stress as a possible source of error, and I noticed that some sensors were off spec after the bare component was being dropped on a hard surface during assembly. Which makes me wonder, whether expansion/contraction of the circuit board with temperature could influence the reading.

Regards,
Adrian

**Comment by smig23** [comment]
Thanks for the feedback Adrian.

The test was done in an room that was not too controlled, but I did ensure that no doors were opened/closed, HVAC was in off etc. and I did note that the temperature/pressure from a weather perspective, was stable.
Good data point on considering the mechanical stress. One thing I didn't consider when soldering the sensor to the PCB was the recommended soldering temperature profile. I manually soldered the device with an hot air and likely the maximum temperature was exceeded and I'm sure the profile wasn't optimum.
I plan on mounting some additional sensors and so I will be conscious of the solder and do some comparisons between boards/sensors. 
The relationship between temperature and pressure change seems to be quite linear ( at least in the range I was observing). Below shows applying a correction of 5.7Pa for each degree C, over about a 10 degree C temperature change. e.g.:
![image](https://user-images.githubusercontent.com/4381963/62992576-f4b1c500-be21-11e9-8806-246225ffa6b9.png)

Blue: Temperature, Red: Uncompensated pressure, Green: Additional compensation applied.

Once again thanks for sharing your thoughts.

Cheers
Ian
